# Usa la imagen oficial de Node.js como base
FROM node:14

# Establece el directorio de trabajo en el contenedor
WORKDIR /usr/src/app

# Copia los archivos de la aplicación
COPY ./node-app/package*.json ./
COPY ./node-app .

# Instala las dependencias
RUN npm install

# Exponer el puerto 3000 para que la aplicación Node.js pueda servir el contenido
EXPOSE 3000

# Comando por defecto para iniciar la aplicación
CMD ["node", "app.js"]
