version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "7000:80"
    volumes:
      - ./html:/usr/share/nginx/html
    restart: always

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "7001:3000"
    restart: always
